### ISSUE TITLE
Warpcast CORS policy change

### ISSUE THREAD

**Issue by artlu99** [pugson/react-farcaster-embed#2]
Has the recent Warpcast CORS policy change broken this component for good?

I am seeing these types of errors in my browser console:

`Access to fetch at 'https://client.warpcast.com/v2/user-thread-casts?castHashPrefix=0x[xxxxxx]&username=[xxx]&limit=5' from origin 'https://[xxx]' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by pugson** [comment]
i'm not getting any errors when testing. what origin are you trying from?

**Comment by artlu99** [comment]
this used to work: https://farchiver.xyz/castimonials

https://github.com/artlu99/farchiver-ssg/blob/main/src/components/Castimonials.tsx

**Comment by pugson** [comment]
can you upgrade to the latest version and try again?

i set up a proxy with https://github.com/pugson/react-farcaster-embed/commit/d29a12419678325819909ed4e3c366827594399f

**Comment by sjanse-dotsur** [comment]
@pugson Just tested it with 1.4.2 and the issue still persists when using the client component. Does not happen on localhost, but as soon as I deploy it to any server, I run into the mentioned issue (removed names and domains, but the original error displays them correctly)

`Access to fetch at 'https://farcaster.tv/v2/user-thread-casts?castHashPrefix=0xXXXXXXX&username=XXXXXXXXXX&limit=3' from origin 'https://mydomain.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
`

I'm using it in a React/Remix project, and I thought about setting up an endpoint within the project itself as a server function, to call the farcast API and retrieve the cast data, bypassing the CORS error. Then I'd pass it down as a prop to the client component, instead of the URL. 

If the CORS issue can't be solved, could we get a prop to pass the data instead of the URL to the client component?

**Comment by pugson** [comment]
@artlu99 @sjanse-dotsur can you try 1.4.7 and let me know if you still get cors errors?

**Comment by sjanse-venturing** [comment]
@pugson yeah! It's working now, thanks a lot for the quick response!

**Comment by sjanse-dotsur** [comment]
@pugson yeah! It's working now, thanks a lot for the quick response!

**Comment by pugson** [comment]
awesome. thanks for bringing it to my attention!
